version: '3'

services:
   db:
     image: mysql:${MYSQL_VERSION}
     volumes:
       - ./${MYSQL_DIRECTORY_NAME}:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   wordpress:
     depends_on:
       - db
     image: wordpress:${WORDPRESS_VERSION}
     volumes:
       - ./${WORDPRESS_DIRECTORY_NAME}:/var/www/html
     ports:
       - "${WORDPRESS_PORT}:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
